export const ERRORS_RETURNED = "ERRORS_RETURNED";
export const ERRORS_LOGGED = "ERRORS_LOGGED";
export const LOGGING_ERROR = "LOGGING_ERROR";
export const ERRORS_CLEARED = "ERRORS_CLEARED";

export const POSTS_LOADING = "POSTS_LOADING";
export const POSTS_ERROR = "POSTS_ERROR";
export const POST_CREATED = "POST_CREATED";
export const POSTS_FETCHED = "POSTS_FETCHED";
export const POST_RETURNED = "POST_RETURNED";
export const POST_UPDATED = "POST_UPDATED";
export const POST_DELETED = "POST_DELETED";